const PATH_ICON = require('../assets/2.0/path/p1.png');
const PATH_ICON9 = require('../assets/2.0/path/p9.png');
const PATH_ICON26 = require('../assets/2.0/path/p26.png');
const PATH_ICON15 = require('../assets/2.0/path/p15.png');
const PATH_ICON23 = require('../assets/2.0/path/p23.png');
const PATH_ICON31 = require('../assets/2.0/path/p31.png');
const PATH_ICON33 = require('../assets/2.0/path/p33.png');
const PATH_ICON37 = require('../assets/2.0/path/p37.png');
const PATH_ICON43 = require('../assets/2.0/path/p43.png');
const PATH_ICON53 = require('../assets/2.0/path/p53.png');
const PATH_ICON59 = require('../assets/2.0/path/p59.png');
const PATH_ICON74 = require('../assets/2.0/path/p74.png');
const PATH_ICON78 = require('../assets/2.0/path/p53.png');
const PATH_ICON80 = require('../assets/2.0/path/p80.png');
const PATH_ICON83 = require('../assets/2.0/path/p83.png');
const PATH_ICON90 = require('../assets/2.0/path/p83.png');
const PATH_ICON106 = require('../assets/2.0/path/p106.png');


const MODEL_ICON = require('../assets/2.0/path/p2.png');
const MODEL_ICON15 = require('../assets/2.0/path/m15.png');
const MODEL_ICON26 = require('../assets/2.0/path/m26.png');
const MODEL_ICON9 = require('../assets/2.0/path/m9.png');
const MODEL_ICON23 = require('../assets/2.0/path/m23.png');
const MODEL_ICON31 = require('../assets/2.0/path/m31.png');
const MODEL_ICON33 = require('../assets/2.0/path/m33.png');
const MODEL_ICON37 = require('../assets/2.0/path/m37.png');
const MODEL_ICON43 = require('../assets/2.0/path/m43.png');
const MODEL_ICON53 = require('../assets/2.0/path/m53.png');
const MODEL_ICON59 = require('../assets/2.0/path/m59.png');
const MODEL_ICON74 = require('../assets/2.0/path/m74.png');
const MODEL_ICON78 = require('../assets/2.0/path/m53.png');
const MODEL_ICON80 = require('../assets/2.0/path/m80.png');
const MODEL_ICON83 = require('../assets/2.0/path/m83.png');
const MODEL_ICON106 = require('../assets/2.0/path/m106.png');
const MODEL_ICON90 = require('../assets/2.0/path/m83.png');

















export interface Lesson {
  id: number;
  icon: any;
  modelIcon?: any;
  title: string;
  chapter: string;
  chapterTitle: string;
  week: number;
  bullets: string[];
  chapterColor: string;
  hintText?: string;
  hintOffsetX?: number;   
  hintOffsetY?: number;
  arrowRotate?: string; 
  arrowTop?: number;    
  arrowLeft?: number;
}

export const HDA_LESSONS: Lesson[] = [

  // ─── Phase 1 | Chapter 1 : Designing Your Mind (Week 1) ───
  {
    id: 1,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Purpose Deconstruction",
    chapter: "Phase 1 | Chapter 1",
    chapterTitle: "Designing Your Mind",
    week: 1,
    chapterColor: "#2D1B69",
    bullets: [
      "Strip away cognitive noise to find your absolute personal clarity and true intent.",
      "Evaluate what specific production niches you are naturally good at.",
      "Isolate the creative landscapes that bring you genuine excitement and daily joy.",
    ],
  },
  {
    id: 2,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Physical Onboarding",
    chapter: "Phase 1 | Chapter 1",
    chapterTitle: "Designing Your Mind",
    week: 1,
    chapterColor: "#2D1B69",
    bullets: [
      "Secure and install a specialized gym membership near your immediate home.",
      "Connect directly with your gym trainer for a personalized physical kickoff routine.",
      "Align physical output consistency to build stamina for deep cognitive workloads.",
    ],
  },
  {
    id: 3,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Analog Habit Mechanics",
    chapter: "Phase 1 | Chapter 1",
    chapterTitle: "Designing Your Mind",
    week: 1,
    chapterColor: "#2D1B69",
    bullets: [
      "Learn Zarna's custom lecture on drawing doodles and analog habit layouts.",
      "Master efficient, structured note-taking habits using tactile pen and paper.",
      "Discover why automated AI tools can never replace the true internal joy of manual planning.",
    ],
  },
  {
    id: 4,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Habit Systemization",
    chapter: "Phase 1 | Chapter 1",
    chapterTitle: "Designing Your Mind",
    week: 1,
    chapterColor: "#2D1B69",
    bullets: [
      "Deconstruct the precise structural benefits and blueprints of custom habit trackers.",
      "Turn loose daily actions into repeatable, bulletproof mental and physical workflows.",
      "Study how physical metric consistency scales your creative business execution loops.",
    ],
  },
  {
    id: 5,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Anti-AI Ideation Matrices",
    chapter: "Phase 1 | Chapter 1",
    chapterTitle: "Designing Your Mind",
    week: 1,
    chapterColor: "#2D1B69",
    bullets: [
      "Select a project idea under strict constraints: No digital products that AI can kill tomorrow.",
      "Pivot parameters toward shared experiences or physical projects like AR systems, card games, or holograms.",
      "Evaluate deep futuristic concepts like a Tarak Mehta Card Game or Herapheri 5 time-travel comic for Product-Market Fit.",
    ],
  },
  {
    id: 6,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Anapan Concentration",
    chapter: "Phase 1 | Chapter 1",
    chapterTitle: "Designing Your Mind",
    week: 1,
    chapterColor: "#2D1B69",
    bullets: [
      "Stabilize mental focus and anxieties using standard Anapan Meditation breath principles.",
      "Use deep focus anchoring to construct a strong internal foundation for your mind.",
      "Calm your workspace psychology to better tackle complex structural design challenges.",
    ],
  },
  {
    id: 7,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Aesthetic Styling Rules",
    chapter: "Phase 1 | Chapter 1",
    chapterTitle: "Designing Your Mind",
    week: 1,
    chapterColor: "#2D1B69",
    bullets: [
      "Complete a professional fashion and image stylist analysis to discover your presentation style.",
      "Identify specific aesthetic styles and wardrobe choices tailored to your body type.",
      "Map an authentic personal style matrix to project high authority to future investors.",
    ],
  },
  {
    id: 8,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Vipasana Registration",
    chapter: "Phase 1 | Chapter 1",
    chapterTitle: "Designing Your Mind",
    week: 1,
    chapterColor: "#2D1B69",
    bullets: [
      "Research, decide upon, and register early at a suitable formal meditation facility.",
      "Lock in your formal 10-day silent meditation journey scheduled at the absolute end of the course.",
      "Establish a rigid timeline boundary to mark your graduation transition into life 2.0.",
    ],
  },
  // ─── Phase 1 | Chapter 2 : FigJam AI & Product Specs (Week 2) ───
  {
    id: 9,
    icon: PATH_ICON9,
    modelIcon: MODEL_ICON9,
    title: "Generative Workspace Workflows",
    chapter: "Phase 1 | Chapter 2",
    chapterTitle: "FigJam AI & Product Specs",
    week: 2,
    chapterColor: "#0F3460",
    bullets: [
      "Discover the fundamentals of FigJam and the native FigJam AI workspace architecture.",
      "Use text prompt blocks to instantly create customized meeting templates, board structures, and visual timelines.",
      "Learn how to add specificity to your AI prompts to dial in exact project layouts in seconds.",
    ],
    hintText: "Hey, FigJam",
    hintOffsetX: 30,  
    hintOffsetY: 60,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 10,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Automated Synthesis & Sorting",
    chapter: "Phase 1 | Chapter 2",
    chapterTitle: "FigJam AI & Product Specs",
    week: 2,
    chapterColor: "#0F3460",
    bullets: [
      "Use FigJam AI to instantly sort messy brainstorm stickies into clean, clear thematic groups.",
      "Hone in on core patterns and automatically summarize extensive board data with a single click.",
      "Convert chaotic group output maps into organized, actionable project next steps.",
    ],
  },
  {
    id: 11,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Metaphysics of Friction",
    chapter: "Phase 1 | Chapter 2",
    chapterTitle: "FigJam AI & Product Specs",
    week: 2,
    chapterColor: "#0F3460",
    bullets: [
      "Study the deep logic of human problems through self-discovery and internal inspection.",
      "Track the core three-part framework: Where does pain sit, why does it happen, and what is its cure?",
      "Take students on an introspective journey to align their startup idea to real market remedies.",
    ],
  },
  {
    id: 12,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "White-Paper Specifications",
    chapter: "Phase 1 | Chapter 2",
    chapterTitle: "FigJam AI & Product Specs",
    week: 2,
    chapterColor: "#0F3460",
    bullets: [
      "Breakdown the basic structure of a corporate white-paper document and why it is made.",
      "Isolate your target user persona and define the precise problem landscape your product addresses.",
      "Script your long-term creative vision to explicitly validate your concept for future market release.",
    ],
  },
  {
    id: 13,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Product Naming & Taglines",
    chapter: "Phase 1 | Chapter 2",
    chapterTitle: "FigJam AI & Product Specs",
    week: 2,
    chapterColor: "#0F3460",
    bullets: [
      "Brainstorm target brand identifiers to get down to a definitive name for your product.",
      "Craft and lock in a sharp, high-impact tagline that represents your core value matrix.",
      "Double-check your core parameters against anti-AI guardrails to ensure permanent viability.",
    ],
  },
  // ─── Phase 1 | Chapter 3 : Figma Foundations & AI Assets (Week 2) ───
  {
    id: 14,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Universal Interface Mindset",
    chapter: "Phase 1 | Chapter 3",
    chapterTitle: "Figma Foundations & AI Assets",
    week: 2,
    chapterColor: "#1B4332",
    bullets: [
      "Learn why every modern design software operates on identical spatial logic.",
      "Map interface patterns common to all viewports using cursors, toolbars, and white space.",
      "Overcome platform choice paralysis by focusing purely on raw creative execution.",
    ],
    // hintText: "Hey, Figma",
    // hintOffsetX: -180,  
    // hintOffsetY: 60,
    // arrowRotate: '195deg', 
    // arrowTop: -20,       
    // arrowLeft: 80,
  },
  {
    id: 15,
    icon: PATH_ICON15,
    modelIcon: MODEL_ICON15,
    title: "AI Image Generation & Prompts",
    chapter: "Phase 1 | Chapter 3",
    chapterTitle: "Figma Foundations & AI Assets",
    week: 2,
    chapterColor: "#1B4332",
    bullets: [
      "Study prompt generation engineering to render ultra-precise, complex artistic visuals.",
      "Master blending visual settings, aspects, and stylization weights using text-to-image engines.",
      "Port customized high-fidelity AI artwork directly into your design environment.",
    ],
    hintText: "AI - Image",
    hintOffsetX: -180,  
    hintOffsetY: 60,
    arrowRotate: '195deg', 
    arrowTop: -20,       
    arrowLeft: 80,
  },
  {
    id: 16,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Vector Logo Systems",
    chapter: "Phase 1 | Chapter 3",
    chapterTitle: "Figma Foundations & AI Assets",
    week: 2,
    chapterColor: "#1B4332",
    bullets: [
      "Explore diverse corporate logo classifications and collect moodboards on Pinterest.",
      "Generate unique reference concepts using tailored asset prompts.",
      "Vectorize shapes using Illustrator path tools and port them cleanly into Figma.",
      "Finalize your production-ready brand logo, name, and tagline matrix.",
    ],
  },
  {
    id: 17,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Visual Hierarchy Mechanics",
    chapter: "Phase 1 | Chapter 3",
    chapterTitle: "Figma Foundations & AI Assets",
    week: 2,
    chapterColor: "#1B4332",
    bullets: [
      "Deconstruct scale, weight, and visual contrast principles used for high-profile assets.",
      "Apply deep color theory matrices to pick palettes that stir exact target human emotions.",
      "Study the step-by-step process of engineering promotional designs for entertainment stars.",
    ],
  },
  {
    id: 18,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "High-Fidelity Artwork Mixing",
    chapter: "Phase 1 | Chapter 3",
    chapterTitle: "Figma Foundations & AI Assets",
    week: 2,
    chapterColor: "#1B4332",
    bullets: [
      "Mix curated Pinterest layout research with raw generated AI textures and images.",
      "Blend layered graphical elements, typography blocks, and masks inside Figma.",
      "Assemble a finished, stylized promotional poster or high-impact brand banner.",
    ],
  },
  {
    id: 19,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Multi-Platform Brand Layouts",
    chapter: "Phase 1 | Chapter 3",
    chapterTitle: "Figma Foundations & AI Assets",
    week: 2,
    chapterColor: "#1B4332",
    bullets: [
      "Construct original brand visual patterns, grid structures, and decorative shapes.",
      "Layout swipeable, multi-frame carousel templates for vertical social media feeds.",
      "Scale asset boundaries to generate uniform Twitter headers and YouTube cover banners.",
    ],
  },
  // ─── Phase 1 | Chapter 4 : Landing Page Strategy & Core AI Systems (Week 3) ───
  {
    id: 20,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Architecture of Intent",
    chapter: "Phase 1 | Chapter 4",
    chapterTitle: "Landing Page Strategy & Core AI",
    week: 3,
    chapterColor: "#9A3324",
    bullets: [
      "Study fundamental conversion metrics to understand why high-performing landing pages are built.",
      "Isolate your target web traffic profiles and define clear visitor expectations.",
      "Establish clean primary actions, deciding whether to make users buy, subscribe, or engage.",
    ],
  },
  {
    id: 21,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Typography Scales & Sizing",
    chapter: "Phase 1 | Chapter 4",
    chapterTitle: "Landing Page Strategy & Core AI",
    week: 3,
    chapterColor: "#9A3324",
    bullets: [
      "Master font styles, type selection scales, and structural web readability.",
      "Standardize average layout type sizing parameters across mobile and desktop banners.",
      "Balance paragraph line-heights and text contrasts to optimize visibility and eye flow.",
    ],
  },
  {
    id: 22,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Art of Stealing & Wireframing",
    chapter: "Phase 1 | Chapter 4",
    chapterTitle: "Landing Page Strategy & Core AI",
    week: 3,
    chapterColor: "#9A3324",
    bullets: [
      "Explore top-tier designer landing pages on Pinterest to gather spatial inspiration.",
      "Deconstruct and blend layout blocks from 5 leading web designs into an original map.",
      "Assemble copy documents spanning your full header, features grid, and footer data.",
    ],
  },
  {
    id: 23,
    icon: PATH_ICON23,
    modelIcon: MODEL_ICON23,
    title: "Figma Make AI Prompts",
    chapter: "Phase 1 | Chapter 4",
    chapterTitle: "Landing Page Strategy & Core AI",
    week: 3,
    chapterColor: "#9A3324",
    bullets: [
      "Master advanced text prompting rules explicitly built for the Figma Make engine.",
      "Instruct generative prompt matrix blocks to instantly output structurally functional landing page mockups.",
      "Rapidly customize layout sections and generated assets inside your design environment.",
    ],
    hintText: "Figma Make",
    hintOffsetX: -180,  
    hintOffsetY: 60,
    arrowRotate: '195deg', 
    arrowTop: -20,       
    arrowLeft: 85,
  },
  // ─── Phase 1 | Chapter 5 : Component Systems & Layout Architecture (Week 3) ───
  {
    id: 24,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Master Component Architecture",
    chapter: "Phase 1 | Chapter 5",
    chapterTitle: "Figma Design Systems & Assembly",
    week: 3,
    chapterColor: "#1A6B5A",
    bullets: [
      "Learn the foundational mechanics of reusable master components and design instances.",
      "Group atom-level building blocks into flexible nested layout modules.",
      "Protect your visual structures by keeping global overrides fully systematic.",
    ],
  },
  {
    id: 25,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Building Responsive Tokens",
    chapter: "Phase 1 | Chapter 5",
    chapterTitle: "Figma Design Systems & Assembly",
    week: 3,
    chapterColor: "#1A6B5A",
    bullets: [
      "Construct unified button matrices, navigation panels, and active link states.",
      "Deploy systematic localized spacing tokens, padding parameters, and column grids.",
      "Connect all variable values together to achieve responsive layout fluidities.",
    ],
  },
  // ─── Phase 1 | Chapter 6 : Responsive Mobile Adaptation (Week 4) ───
  {
    id: 26,
    icon: PATH_ICON26,
    modelIcon: MODEL_ICON26,
    title: "The Mobile Down-Scaling Blueprint",
    chapter: "Phase 1 | Chapter 6",
    chapterTitle: "Mobile App UI/UX Architecture",
    week: 4,
    chapterColor: "#784212",
    bullets: [
      "Convert your established high-fidelity desktop website assets down into a native mobile workspace layout.",
      "Restructure wide grid features into vertical stack structures to streamline thumb-driven interaction maps.",
      "Learn standard mobile viewport parameters, target boundaries, scale variations, and thumb-zone safety grids.",
    ],
    hintText: "Mobile UI/UX",
    hintOffsetX: 30,  
    hintOffsetY: 60,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 27,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Mobile Tap Targets & Type Tuning",
    chapter: "Phase 1 | Chapter 6",
    chapterTitle: "Mobile App UI/UX Architecture",
    week: 4,
    chapterColor: "#784212",
    bullets: [
      "Reposition typography scales and margins to maximize visibility and accessibility on small screens.",
      "Size navigation components and active button zones to standard pixel sizes to prevent user touch errors.",
      "Build an information architecture spread systematically across 3 to 4 distinct mobile view panels.",
    ],
  },
  {
    id: 28,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Advanced Prototype Animations",
    chapter: "Phase 1 | Chapter 6",
    chapterTitle: "Mobile App UI/UX Architecture",
    week: 4,
    chapterColor: "#784212",
    bullets: [
      "Map interactive wiring paths across panels to build a functional user flow mockup demonstration.",
      "Use smart animate parameters to configure smooth, realistic modal slide-ups and layout sweeps.",
      "Cast your active prototype directly into the Figma Mirror application to audit and eliminate friction.",
    ],
  },
  {
    id: 29,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Device Mirroring & Tuning",
    chapter: "Phase 1 | Chapter 6",
    chapterTitle: "Mobile App UI/UX Architecture",
    week: 4,
    chapterColor: "#784212",
    bullets: [
      "Cast your finalized mockup canvas directly into the Figma Mirror application.",
      "Audit alignment mistakes, balance font weights, and eliminate interface friction.",
      "Lock down a pixel-perfect, production-ready blueprint ready for Framer development.",
    ],
  },
  // ─── Phase 1 | Chapter 7 : Design.md & Google Project Stitch AI (Week 4) ───
  {
    id: 30,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Design.md Specification Architecture",
    chapter: "Phase 1 | Chapter 7",
    chapterTitle: "Generative Design System Automation",
    week: 4,
    chapterColor: "#4A235A",
    bullets: [
      "Master Markdown rules required to author a professional software design specification text file.",
      "Learn to systematically serialize and export your active Figma design token values into an organized, flat text layout.",
      "Define global variables for color families, typographic steps, padding boundaries, and aesthetic styles.",
    ],
  },
  {
    id: 31,
    icon: PATH_ICON31,
    modelIcon: MODEL_ICON31,
    title: "Google Project Stitch Prompt Engineering",
    chapter: "Phase 1 | Chapter 7",
    chapterTitle: "Generative Design System Automation",
    week: 4,
    chapterColor: "#4A235A",
    bullets: [
      "Learn the foundational prompt syntax to utilize Google Project Stitch AI as an interactive co-pilot engine.",
      "Inject your custom exported Design.md text parameters directly into the context memory of the AI node.",
      "Train the system to deeply understand your baseline color rules, geometry choices, and style values.",
    ],
    hintText: "Google Stitch",
    hintOffsetX: -190,  
    hintOffsetY: 60,
    arrowRotate: '200deg', 
    arrowTop: -20,       
    arrowLeft: 95,
  },
  {
    id: 32,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Consistent Variable Design Generation",
    chapter: "Phase 1 | Chapter 7",
    chapterTitle: "Generative Design System Automation",
    week: 4,
    chapterColor: "#4A235A",
    bullets: [
      "Instruct the Stitch engine to output completely new asset variants matching your exact Design.md document rules.",
      "Use generative prompt adjustments to automatically produce themed dark-mode files and multi-device templates.",
      "Port your finalized, consistent asset layers back into Figma to complete your verified universal brand engine.",
    ],
  },
  // ─── Phase 2 | Chapter 8 : Framer Workspace Foundations (Week 5) ───
  {
    id: 33,
    icon: PATH_ICON33,
    modelIcon: MODEL_ICON33,
    title: "The Development Canvas Mindset",
    chapter: "Phase 2 | Chapter 8",
    chapterTitle: "Figma-to-NoCode Translation",
    week: 5,
    chapterColor: "#2D1B69",
    bullets: [
      "Explore the complete Framer interface, breaking down Pages, Layers, and the global Assets library.",
      "Master the operational logic of code-free web environments and production staging fields.",
      "Safely navigate workspace controls, including staging invite links, preview states, and live publishing loops.",
    ],
    hintText: "Framer",
    hintOffsetX: 30,  
    hintOffsetY: 60,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 34,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Responsive Breakdown Mechanics",
    chapter: "Phase 2 | Chapter 8",
    chapterTitle: "Figma-to-NoCode Translation",
    week: 5,
    chapterColor: "#2D1B69",
    bullets: [
      "Set up standard viewport container blocks to build uniform desktop, tablet, and mobile breakpoints.",
      "Use pre-built structure layouts to securely convert raw graphic ideas into real web boxes.",
      "Construct local design systems linking font hierarchies and color tokens together.",
    ],
  },
  {
    id: 35,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Figma HTML Porting Workflows",
    chapter: "Phase 2 | Chapter 8",
    chapterTitle: "Figma-to-NoCode Translation",
    week: 5,
    chapterColor: "#2D1B69",
    bullets: [
      "Deploy specialized plugins to quickly copy structural graphic assets directly from your Figma artboards.",
      "Import active design system assets into Framer while preserving core layout layer depths.",
      "Debug broken bounding geometry, fix text line anomalies, and align scaling factors.",
    ],
  },
  // ─── Phase 2 | Chapter 9 : Generative Framer Workshop Modules (Week 5) ───
  {
    id: 36,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Framer Workshop Interface Onboarding",
    chapter: "Phase 2 | Chapter 9",
    chapterTitle: "AI Component Engineering Masterclass",
    week: 5,
    chapterColor: "#0F3460",
    bullets: [
      "Open the Framer Workshop panel to explore its dedicated AI design workspace engine and learn standard logic parameters.",
      "Write text prompt scripts inside the workshop console to output functional web components, customized layout grids, nav arrays, and footer variations instantly.",
      "Use conversational prompts to program smart hover transitions, active click parameters, and complex canvas entrance sequences.",
    ],
  },
  // ─── Phase 2 | Chapter 10 : Generative 3D Modeling Systems (Week 6) ───
  {
    id: 37,
    icon: PATH_ICON37,
    modelIcon: MODEL_ICON37,
    title: "Text-to-3D Generative Logic",
    chapter: "Phase 2 | Chapter 10",
    chapterTitle: "Generative Spatial Engineering",
    week: 6,
    chapterColor: "#1B4332",
    bullets: [
      "Learn foundational prompt mechanics to output lightweight, web-optimized 3D shapes from raw text descriptions.",
      "Utilize text-to-3D and image-to-3D engines within browser-based workspaces to rapidly build product drafts.",
      "Bypass steep traditional software learning curves to quickly materialize your futuristic project concepts.",
    ],
    hintText: "Spline, 3D",
    hintOffsetX: 30,  
    hintOffsetY: 50,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 38,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "AI Texture Mapping & PBR Materials",
    chapter: "Phase 2 | Chapter 10",
    chapterTitle: "Generative Spatial Engineering",
    week: 6,
    chapterColor: "#1B4332",
    bullets: [
      "Generate high-definition textures and physically-based rendering (PBR) material maps using text commands.",
      "Adjust material values including roughness, metallic shine, and environmental lighting variables.",
      "Synchronize the aesthetic details of your models with your predefined project style specifications.",
    ],
  },
  {
    id: 39,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Mesh Optimization & Rigging",
    chapter: "Phase 2 | Chapter 10",
    chapterTitle: "Generative Spatial Engineering",
    week: 6,
    chapterColor: "#1B4332",
    bullets: [
      "Automatically optimize structural topology to ensure hyper-fast browser loading times on live landing pages.",
      "Use automated AI skinning and rigging controls to prepare your generated assets for interaction maps.",
      "Clean up geometry boundaries and export assets into standardized production formats like GLB or FBX.",
    ],
  },
  // ─── Phase 2 | Chapter 11 : Production Integration Architecture (Week 6) ───
  {
    id: 40,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Event-Driven State Machines",
    chapter: "Phase 2 | Chapter 11",
    chapterTitle: "Framer 3D Interactivity & Hosting",
    week: 6,
    chapterColor: "#9A3324",
    bullets: [
      "Set up standard base properties and variant states for your models without writing code.",
      "Wire up event triggers to drive interactive loops based on user mouse movements and click instances.",
      "Configure camera bounds and directional constraints to structure immersive object viewports.",
    ],
  },
  {
    id: 41,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "No-Code Framer Embedding",
    chapter: "Phase 2 | Chapter 11",
    chapterTitle: "Framer 3D Interactivity & Hosting",
    week: 6,
    chapterColor: "#9A3324",
    bullets: [
      "Export your live interactive asset models using secure staging URLs and embed scripts.",
      "Inject your spatial objects directly into responsive container boxes inside your Framer layout tree.",
      "Calibrate component width boundaries and aspect properties to protect multi-device screen fluidities.",
    ],
  },
  {
    id: 42,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Kinetic Scroll Actions",
    chapter: "Phase 2 | Chapter 11",
    chapterTitle: "Framer 3D Interactivity & Hosting",
    week: 6,
    chapterColor: "#9A3324",
    bullets: [
      "Synchronize model rotation steps and spatial scales with real-time browser scrolling parameters.",
      "Build interactive transition paths where objects organically unfold or transform as viewers traverse your site.",
      "Run layout tests to eliminate tracking latency, optimize loading performance, and publish to your custom domain.",
    ],
  },
  // ─── Phase 2.5 | Chapter 1 : Advanced Vibe Coding with Claude (Week 7) ───
  {
    id: 43,
    icon: PATH_ICON43,
    modelIcon: MODEL_ICON43,
    title: "The Vibe Coding Terminal Mindset",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Shift from conversational chatbot windows to an intense, multi-file local vibe-coding workspace.",
      "Master the Claude Command Line Interface (CLI) environment to handle complex background automation runs.",
      "Pipe live terminal logs and script lines into your workspace to audit background executions.",
    ],
    hintText: "Claude Terminal",
    hintOffsetX: 30,  
    hintOffsetY: 50,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 44,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Context Window Engineering",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Set up deep context windows to prevent token loss across hours of complex workspace development.",
      "Isolate high-volume system operations and file outputs into specialized context splits.",
      "Deploy prompt caches and token compactors to optimize processing execution costs.",
    ],
  },
  {
    id: 45,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The CLAUDE.md Blueprint",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Write your master local CLAUDE.md configuration file inside your project's root folder.",
      "Hardcode architecture guidelines, design parameters, and review check-lists into the AI's core memory.",
      "Teach the workspace agent to build automated session history memory to remember commands.",
    ],
  },
  {
    id: 46,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Building Custom Skills",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Author specialized SKILL.md playbooks to extend your agent's domain capabilities.",
      "Package repetitive visual design reviews and structural staging pushes into single short custom tasks.",
      "Share verified, automated team skills across your shared workspace repository safely.",
    ],
  },
  {
    id: 47,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The MCP Directory System",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Learn Model Context Protocol (MCP) standards to safely link your AI straight to your local asset folders.",
      "Use secure protocol tunnels to bypass private company network firewalls responsibly.",
      "Wire external tool directory frameworks into your active model instance via system configurations.",
    ],
  },
  {
    id: 48,
    icon: PATH_ICON26,
    modelIcon: MODEL_ICON26,
    title: "Figma Connectors & Asset Sync",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Connect your live Figma design component databases using official workspace context connectors.",
      "Read web typography matrices, local layout tokens, and UI styles directly into your prompt run.",
      "Automate cross-app workflow queries from Figma documents directly into no-code development fields.",
    ],
    hintText: "Figma Connectors 🛠️",
    hintOffsetX: -230,  
    hintOffsetY: 50,
    arrowRotate: '200deg', 
    arrowTop: -20,       
    arrowLeft: 135,
  },
  {
    id: 49,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Google Workspace & Product Integration",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Synchronize multi-app documentation spanning Google Drive files, Notion notes, and Slack arrays.",
      "Pull user research data and startup specifications into active AI memory with a single click.",
      "Automate multi-tool searches to find and parse product assets scattered across multiple networks.",
    ],
  },
  {
    id: 50,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Persistent Cowork Staging Task Loop",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Switch from normal chat loops to the multi-step Claude Cowork persistent desktop agent workspace.",
      "Describe complex goals in plain English and let the desktop agent outline and execute its own plan.",
      "Interact with local folders and apps to group, classify, and sort assets natively on your machine.",
    ],
  },
  {
    id: 51,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Deploying Pre-Built Plugin Packages",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Install specialized pre-packaged business, legal, and engineering workflow plug-ins.",
      "Execute instant slash commands like /data:analyze or /marketing:metrics-review.",
      "Use auto-sorting tools to clean up files and summarize large numbers of project research sheets.",
    ],
  },
  {
    id: 52,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Orchestrating Sub-Agent Teams",
    chapter: "Phase 2.5 | Chapter 1",
    chapterTitle: "Claude Local Terminal & Context Engineering",
    week: 7,
    chapterColor: "#1A6B5A",
    bullets: [
      "Spawn separate parallel sub-agent workers to run isolated workspace tasks at the same time.",
      "Direct a master lead agent to split complex assignments, manage sub-tasks, and merge results.",
      "Set up recurring morning routines to audit changes and write updates on managed infrastructure.",
    ],
  },
  // ─── Phase 2.5 | Chapter 2 : ChatGPT Deep Research (Week 8) ───
  {
    id: 53,
    icon: PATH_ICON53,
    modelIcon: MODEL_ICON53,
    title: "The Deep Research Engine Workflows",
    chapter: "Phase 2.5 | Chapter 2",
    chapterTitle: "Advanced Reasoning & Research Systems",
    week: 8,
    chapterColor: "#784212",
    bullets: [
      "Initialize multi-step, autonomous web research loops using ChatGPT's native Deep Research architecture.",
      "Learn to structure deep discovery questions to direct the AI agent to dive into market niches over hours.",
      "Synthesize generated research paths down to hyper-detailed competitive analysis briefs for your business.",
    ],
    hintText: "ChatGPT’ ✨",
    hintOffsetX: 30,  
    hintOffsetY: 50,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 54,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Advanced Reasoning & Chain-of-Thought",
    chapter: "Phase 2.5 | Chapter 2",
    chapterTitle: "Advanced Reasoning & Research Systems",
    week: 8,
    chapterColor: "#784212",
    bullets: [
      "Master advanced prompt design paradigms utilizing the reasoning modes of ChatGPT o-series models.",
      "Force the system to execute hidden background chain-of-thought protocols before outputting response steps.",
      "Debug flaws, technical contradictions, and logic blindspots across complex operational plans.",
    ],
  },
  {
    id: 55,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Dynamic Memory Calibration",
    chapter: "Phase 2.5 | Chapter 2",
    chapterTitle: "Advanced Reasoning & Research Systems",
    week: 8,
    chapterColor: "#784212",
    bullets: [
      "Use system profile prompts to permanently feed your product specifications into the AI's core profile memory.",
      "Learn to update, clear, or tweak personal background facts to scale customized long-term outputs.",
      "Build persistent baseline style constraints that track automatically across separate new chat rooms.",
    ],
  },
  // ─── Phase 2.5 | Chapter 3 : ChatGPT Desktop App Connectors (Week 8) ───
  {
    id: 56,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Desktop App Context Workspace",
    chapter: "Phase 2.5 | Chapter 3",
    chapterTitle: "Cross-App Production Automation",
    week: 8,
    chapterColor: "#4A235A",
    bullets: [
      "Set up and secure the ChatGPT desktop app environment directly linked to your active code editors.",
      "Enable system-level view context parameters so the AI co-pilot can read and audit raw open script boxes.",
      "Use universal shortcuts and fast hotkeys to parse, update, and fix software configurations instantly.",
    ],
  },
  {
    id: 57,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Canva & Figma On-The-Spot Systems",
    chapter: "Phase 2.5 | Chapter 3",
    chapterTitle: "Cross-App Production Automation",
    week: 8,
    chapterColor: "#4A235A",
    bullets: [
      "Link the Canva workspace connector to instantly map raw data into finished investor presentation decks.",
      "Connect ChatGPT straight to Figma to run automated reviews on active visual layout architectures.",
      "Prompt text commands to quickly adjust visual structures, update layer hierarchies, and change font sets.",
    ],
  },
  {
    id: 58,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Adobe Automation & Asset Creation",
    chapter: "Phase 2.5 | Chapter 3",
    chapterTitle: "Cross-App Production Automation",
    week: 8,
    chapterColor: "#4A235A",
    bullets: [
      "Connect your Adobe account natively to ChatGPT to drive background layout runs via text lines.",
      "Automate graphic asset generation and heavy background filters inside Adobe Express and Photoshop.",
      "Port your completed, automated visual layers back into your Framer canvas files smoothly.",
    ],
  },
  // ─── Phase 2.5 | Chapter 4 : Google AI Studio (Week 9) ───
  {
    id: 59,
    icon: PATH_ICON59,
    modelIcon: MODEL_ICON59,
    title: "Hands-Free Ambient Brainstorming",
    chapter: "Phase 2.5 | Chapter 4",
    chapterTitle: "Hands-Free Multimodal Interaction",
    week: 9,
    chapterColor: "#2D1B69",
    bullets: [
      "Configure continuous, non-stop voice conversations with Gemini using native microphone inputs.",
      "Master expressing complex startup strategies, layout structures, and loose logic ideas fluently without stopping to type.",
      "Learn to capture real-time ambient thoughts and convert conversational audio tracks directly into clear project prompt inputs.",
    ],
    hintText: "Google AI Studio✨",
    hintOffsetX: 30,  
    hintOffsetY: 50,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 60,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Full-Stack Split-Architecture Apps",
    chapter: "Phase 2.5 | Chapter 4",
    chapterTitle: "Hands-Free Multimodal Interaction",
    week: 9,
    chapterColor: "#2D1B69",
    bullets: [
      "Setup a complete multi-view web platform containing separate, fully functional Client-Side interfaces and Admin-Side control frameworks.",
      "Write text prompt matrix chains inside Google AI Studio to instantly generate responsive React code architectures.",
      "Inject your pre-built Design.md text parameter files to instruct the engine to style the application exactly to your brand rules.",
    ],
  },
  {
    id: 61,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Interactive WebGL & Spatial Engineering",
    chapter: "Phase 2.5 | Chapter 4",
    chapterTitle: "Hands-Free Multimodal Interaction",
    week: 9,
    chapterColor: "#2D1B69",
    bullets: [
      "Prompt Google AI Studio to write high-performance 3D WebGL script structures and interactive canvas components.",
      "Embed your web-optimized custom 3D design models natively into your code layouts without losing execution speed.",
      "Build interactive browser-based games and immersive spatial landing page features that respond instantly to mouse actions.",
    ],
  },
  // ─── Phase 2.5 | Chapter 5 : Google Cloud Staging & Firebase (Week 9) ───
  {
    id: 62,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Firebase Authentication & Backend Sync",
    chapter: "Phase 2.5 | Chapter 5",
    chapterTitle: "Production Backends & Cloud Operations",
    week: 9,
    chapterColor: "#0F3460",
    bullets: [
      "Connect your Google AI Studio project files directly to a scalable backend database environment using Firebase integration.",
      "Implement secure system authentication paths enabling users to execute instant 'Sign In with Google' login flows.",
      "Set up standard security protocols and local variables to responsibly manage live data storage rules.",
    ],
  },
  {
    id: 63,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Google Cloud Network Mapping",
    chapter: "Phase 2.5 | Chapter 5",
    chapterTitle: "Production Backends & Cloud Operations",
    week: 9,
    chapterColor: "#0F3460",
    bullets: [
      "Navigate the Google Cloud Console to provision web project instances and configure structural project endpoints.",
      "Search for, purchase, and lock down your startup's dedicated official custom website domain name framework.",
      "Map DNS routing settings to bind your live AI Studio codebase to your domain name, making it accessible on the live web.",
    ],
  },
  {
    id: 64,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Google Analytics Metric Tracking",
    chapter: "Phase 2.5 | Chapter 5",
    chapterTitle: "Production Backends & Cloud Operations",
    week: 9,
    chapterColor: "#0F3460",
    bullets: [
      "Embed Google Analytics tracking tags directly into your application's code structure to capture live visitor activities.",
      "Construct clean dashboard panels to monitor active session numbers, geographic traffic streams, and user retention curves.",
      "Audit live data metrics to evaluate product-market fit and optimize your platform for real-world production releases.",
    ],
  },
  // ─── Phase 2.5 Expert | Chapter 1 : Claude Code Terminal (Week 10) ───
  {
    id: 65,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Agentic Terminal Workspace",
    chapter: "Phase 2.5 Expert | Chapter 1",
    chapterTitle: "Claude Code Terminal Orchestration",
    week: 10,
    chapterColor: "#1B4332",
    bullets: [
      "Set up local dependencies (Node.js and Git) and install the native Claude Code binary directly into your system terminal.",
      "Run authentication paths using secure Console authorization loops to enable pre-paid centralized cost tracking profiles.",
      "Master essential interactive launch flags and shorthand console commands like claude or claude -p.",
    ],
  },
  {
    id: 66,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Explore-Plan-Confirm Engine",
    chapter: "Phase 2.5 Expert | Chapter 1",
    chapterTitle: "Claude Code Terminal Orchestration",
    week: 10,
    chapterColor: "#1B4332",
    bullets: [
      "Trigger Claude Code's full agentic loop to explore project trees, write structural plans, and await manual approval lines.",
      "Use conversational prompts to command multi-file changes, automatic styling fixes, and layout alterations at the same time.",
      "Utilize built-in session tools like /compact or /clear to manage context memory and reduce usage costs.",
    ],
  },
  {
    id: 67,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Global Open Source Repo Grafting",
    chapter: "Phase 2.5 Expert | Chapter 1",
    chapterTitle: "Claude Code Terminal Orchestration",
    week: 10,
    chapterColor: "#1B4332",
    bullets: [
      "Use text commands to instruct the agent to crawl, read, and completely explain a raw open-source GitHub project repository.",
      "Extract layout files, functional design pieces, and code architectures found across the web.",
      "Merge and graft those external features cleanly into your live app files without breaking background settings.",
    ],
  },
  // ─── Phase 2.5 Expert | Chapter 2 : MCP Automation Systems (Week 10) ───
  {
    id: 68,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The MCP Configuration Architecture",
    chapter: "Phase 2.5 Expert | Chapter 2",
    chapterTitle: "MCP Server Integrations",
    week: 10,
    chapterColor: "#9A3324",
    bullets: [
      "Learn Model Context Protocol (MCP) definitions and run terminal commands to link external servers directly into your agent.",
      "Map secure protocol routing variables inside the root system settings file to give your agent permission to use real-world tools.",
      "Run live diagnostics to confirm data links, resolve shell script execution errors, and verify tool access.",
    ],
  },
  {
    id: 69,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Figma & Marketing MCP Connectors",
    chapter: "Phase 2.5 Expert | Chapter 2",
    chapterTitle: "MCP Server Integrations",
    week: 10,
    chapterColor: "#9A3324",
    bullets: [
      "Link the Figma MCP server to allow your terminal agent to read layout variables, frames, and typography maps directly.",
      "Connect the Meta Ads or marketing protocol to pull campaign records, monitor asset data, and track metrics from your terminal.",
      "Build automated workflows where design changes in Figma automatically trigger updates on landing pages.",
    ],
  },
  {
    id: 70,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Cloud Console & Infrastructure Operations",
    chapter: "Phase 2.5 Expert | Chapter 2",
    chapterTitle: "MCP Server Integrations",
    week: 10,
    chapterColor: "#9A3324",
    bullets: [
      "Integrate Google Cloud and specialized cloud infrastructure MCP servers directly into your active console engine.",
      "Instruct the agent to run code deployments, track server instances, and audit project statuses using plain English commands.",
      "Leverage built-in git tools to commit changes, log errors, and push verified code directly to live staging platforms.",
    ],
  },
  // ─── Phase 2.5 Expert | Chapter 3 : Google Antigravity (Week 11) ───
  {
    id: 71,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The AI Studio Export-to-Antigravity Flow",
    chapter: "Phase 2.5 Expert | Chapter 3",
    chapterTitle: "Transitioning to Heavy Production",
    week: 11,
    chapterColor: "#1A6B5A",
    bullets: [
      "Execute the official Google I/O 2026 context export sequence to bring your web-built AI Studio prototype into Antigravity 2.0.",
      "Port over your full conversational history and prompt states alongside the source code with a single click.",
      "Connect Antigravity 2.0 safely to your project's local codebases and root folders under a clean project structure.",
    ],
  },
  {
    id: 72,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Android Studio CLI Onboarding",
    chapter: "Phase 2.5 Expert | Chapter 3",
    chapterTitle: "Transitioning to Heavy Production",
    week: 11,
    chapterColor: "#1A6B5A",
    bullets: [
      "Install and configure the new stable Android CLI 1.0 utility onto your machine's system directory.",
      "Allow your Antigravity agent to communicate with Android Studio's core compilation engine without manually opening the heavy IDE UI.",
      "Run terminal setup scripts to establish semantic symbol resolutions and lint mapping flags for code verification.",
    ],
  },
  {
    id: 73,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Building with Parallel Agent Teams",
    chapter: "Phase 2.5 Expert | Chapter 3",
    chapterTitle: "Transitioning to Heavy Production",
    week: 11,
    chapterColor: "#1A6B5A",
    bullets: [
      "Upgrade your setup to the $100/mo Google AI Ultra plan to access higher usage limits and full agent coordination features.",
      "Direct your primary Antigravity agent to spawn separate parallel subagents to handle focused sub-tasks.",
      "Run background tasks asynchronously so you can keep iterating on your front-end layout components.",
    ],
  },
  // ─── Phase 2.5 Expert | Chapter 4 : Gemini-Driven App Distribution (Week 11) ───
  {
    id: 74,
    icon: PATH_ICON74,
    modelIcon: MODEL_ICON74,
    title: "Agentic Jetpack Compose Refactoring",
    chapter: "Phase 2.5 Expert | Chapter 4",
    chapterTitle: "Jetpack Compose & Google Play Deployment",
    week: 11,
    chapterColor: "#784212",
    bullets: [
      "Command your agent to completely refactor loose user views into clean, native Jetpack Compose Kotlin structures.",
      "Use advanced Android skills to let the agent render live visual layout previews of your screens directly.",
      "Run automated end-to-end user path tests inside your system terminal to audit user flow loops.",
    ],
     hintText: "Jetpack Compose",
    hintOffsetX: 30,  
    hintOffsetY: 50,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 75,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Google Play Production Publishing",
    chapter: "Phase 2.5 Expert | Chapter 4",
    chapterTitle: "Jetpack Compose & Google Play Deployment",
    week: 11,
    chapterColor: "#784212",
    bullets: [
      "Wire up your active workspace agent directly to your Google Play Developer Console profile settings.",
      "Automate code building, bundle key signing, and version verification tests through simple command terminal prompts.",
      "Publish your completed native Android mobile application straight to the official internal testing tracks.",
    ],
  },
  {
    id: 76,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Android Studio Migration Assistant",
    chapter: "Phase 2.5 Expert | Chapter 4",
    chapterTitle: "Jetpack Compose & Google Play Deployment",
    week: 11,
    chapterColor: "#784212",
    bullets: [
      "Initialize the new Android Studio Migration Assistant agent to map your code structure onto cross-platform targets.",
      "Let the migration agent read your native Kotlin layouts and rewrite them into clean iOS Swift architectures.",
      "Package your newly cross-migrated visual assets and upload the completed app bundle straight to Apple's App Store Connect portal.",
    ],
  },
  // ─── Phase 3 | Chapter 1 : Generative Pre-Production (Week 12) ───
  {
    id: 77,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Imagination Translation Matrix",
    chapter: "Phase 3 | Chapter 1",
    chapterTitle: "Multi-Source Image Composition",
    week: 12,
    chapterColor: "#4A235A",
    bullets: [
      "Study how to scrape and collect raw layout geometries and framing inspirations from Pinterest.",
      "Learn to combine distinct reference styles together to formulate one unified visual system in your head.",
      "Feed multi-reference layout blueprints into ChatGPT Images 2.0 to instantly materialize your concept.",
    ],
    
  },
  {
    id: 78,
    icon: PATH_ICON78,
    modelIcon: MODEL_ICON78,
    title: "ChatGPT Images 2.0 Token Control",
    chapter: "Phase 3 | Chapter 1",
    chapterTitle: "Multi-Source Image Composition",
    week: 12,
    chapterColor: "#4A235A",
    bullets: [
      "Master advanced text-to-image prompt parameters utilizing the native ChatGPT Images 2.0 engine.",
      "Command aspect changes, camera lenses, lighting styles, and compositional values without code.",
      "Control iteration prompts to tweak specific elements of a generated picture while keeping the rest consistent.",
    ],
    hintText: "Image 2.0’ ✨",
    hintOffsetX: -195,  
    hintOffsetY: 50,
    arrowRotate: '200deg', 
    arrowTop: -20,       
    arrowLeft: 95,
  },
  {
    id: 79,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Google AI Studio Multi-Model Audits",
    chapter: "Phase 3 | Chapter 1",
    chapterTitle: "Multi-Source Image Composition",
    week: 12,
    chapterColor: "#4A235A",
    bullets: [
      "Initialize side-by-side prompt generation parameters using the Google AI Studio developer playground.",
      "Switch between diverse production models to test how different network weights render identical phrases.",
      "Execute rapid layout tests to select the absolute best image outputs for your marketing materials.",
    ],
  },
  {
    id: 80,
    icon: PATH_ICON80,
    modelIcon: MODEL_ICON80,
    title: "Adobe Firefly Boards Setup",
    chapter: "Phase 3 | Chapter 1",
    chapterTitle: "Multi-Source Image Composition",
    week: 12,
    chapterColor: "#4A235A",
    bullets: [
      "Launch an interactive, AI-powered workspace using the brand new Adobe Firefly Board framework.",
      "Structure loose design thoughts, vector color palettes, text notes, and mockups in one collaborative space.",
      "Map layout structures sequentially to prepare a professional visual roadmap for your media.",
    ],
    hintText: "Adobe Firefly",
    hintOffsetX: -195,  
    hintOffsetY: 50,
    arrowRotate: '200deg', 
    arrowTop: -20,       
    arrowLeft: 95,
  },
  {
    id: 81,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Generative Firefly Model Blending",
    chapter: "Phase 3 | Chapter 1",
    chapterTitle: "Multi-Source Image Composition",
    week: 12,
    chapterColor: "#4A235A",
    bullets: [
      "Deploy specialized Adobe text-to-image variations directly inside your structured project board rows.",
      "Run style transfers and vector alignment controls to ensure all generated panels look visually coherent.",
      "Finalize an immersive, production-ready marketing storyboard to guide your physical video shoot frames.",
    ],
  },
  {
    id: 82,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Google Flow Cinematic Prompting",
    chapter: "Phase 3 | Chapter 1",
    chapterTitle: "Multi-Source Image Composition",
    week: 12,
    chapterColor: "#4A235A",
    bullets: [
      "Onboard into Google Flow (VideoFX/Vids) to translate raw text lines into stylized video assets.",
      "Master camera movement syntax (pans, zooms, track motions) using advanced video prompt engineering.",
      "Generate 3 to 5 second high-fidelity atmospheric AI video clips to deploy across your marketing pipeline.",
    ],
  },
  // ─── Phase 3 | Chapter 2 : Storytelling Architecture (Week 13) ───
  {
    id: 83,
    icon: PATH_ICON83,
    modelIcon: MODEL_ICON83,
    title: "12 Principles of Animation for Social Media",
    chapter: "Phase 3 | Chapter 2",
    chapterTitle: "Universal Content Planning & Shooting",
    week: 13,
    chapterColor: "#2D1B69",
    bullets: [
      "Deconstruct the classic 12 Principles of Animation (Squash & Stretch, Anticipation, Timing) for modern video assets.",
      "Map kinetic physics rules onto standard layouts to ensure your text transitions, graphic pop-ins, and scene cuts feel natural.",
      "Learn to engineer rapid, attention-grabbing visual pacing that hooks viewers instantly within the first 3 seconds.",
    ],
     hintText: "After Effects , Motion Magic ✨",
    hintOffsetX: 30,  
    hintOffsetY: 50,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 84,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Multi-Format Production Roadmap",
    chapter: "Phase 3 | Chapter 2",
    chapterTitle: "Universal Content Planning & Shooting",
    week: 13,
    chapterColor: "#2D1B69",
    bullets: [
      "Build a bulletproof pre-production checklist that works for any video format, from 9:16 Instagram Reels to complex motion graphic tracks.",
      "Plan your timeline markers, sound effects, text cues, and asset placeholders before touching any editing software.",
      "Connect loose creative ideas into a highly systematic execution plan to eliminate editing room confusion.",
    ],
  },
  // ─── Phase 3 | Chapter 3 : Generative AI Storyboarding (Week 13) ───
  {
    id: 85,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Generative Frame Assembly Pipeline",
    chapter: "Phase 3 | Chapter 3",
    chapterTitle: "Conversational Frameworks & Visual Storyboards",
    week: 13,
    chapterColor: "#0F3460",
    bullets: [
      "Hold real-time conversational prompt runs with Gemini 2.0 or ChatGPT Images 2.0 to transform your loose script ideas into sequential, highly accurate visual panels.",
      "Master style-locking tokens and narrative continuity variables to ensure that characters, lighting aesthetics, and backgrounds stay completely uniform across every single scene frame.",
      "Port your completed multi-frame generative panels directly into a collaborative Figma canvas layout to arrange, group, and map out the exact chronological structure of your final video asset.",
    ],
  },
  // ─── Phase 3 | Chapter 4 : On-Camera Presence (Week 14) ───
  {
    id: 86,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Voice Projection & Continuous Take Workflow",
    chapter: "Phase 3 | Chapter 4",
    chapterTitle: "Screen Confidence & Physical Production",
    week: 14,
    chapterColor: "#1B4332",
    bullets: [
      "Learn to use your phone or camera to shoot high-quality, stable baseline source footage with proper frame alignment.",
      "Set up a functional local studio space using a simple mobile stand, clean framing, and accessible layout baselines.",
      "Master advanced vocal delivery rules, breathing patterns, and posture ticks to project an unshakeable, highly confident presence.",
      "Implement the 'Infinite Rolling Take' routine, allowing the camera to record continuously until you capture your absolute perfect shot.",
    ],
  },
  // ─── Phase 3 | Chapter 5 : Post-Production in Premiere Pro (Week 14) ───
  {
    id: 87,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Premiere Pro Interface & Media Ingestion",
    chapter: "Phase 3 | Chapter 5",
    chapterTitle: "Non-Linear Editing System Workspace",
    week: 14,
    chapterColor: "#9A3324",
    bullets: [
      "Onboard into the native Premiere Pro interface layout, mapping the Source Monitor, Program Monitor, Project Panels, and Timeline tracks.",
      "Implement a professional bin structure inside your project window to organize raw camera multi-takes, audio logs, and graphics.",
      "Ingest your locally shot video clips directly into high-performance, frame-accurate sequences matching native target resolution parameters.",
    ],
  },
  {
    id: 88,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Text-Based Transcription & Raw Cutting",
    chapter: "Phase 3 | Chapter 5",
    chapterTitle: "Non-Linear Editing System Workspace",
    week: 14,
    chapterColor: "#9A3324",
    bullets: [
      "Initialize Premiere Pro's AI Transcribe engine to instantly convert your recorded rolling spoken takes into text scripts.",
      "Use text-based editing to quickly delete text lines, clearing dead spaces, filler words, and bad takes directly from the source track.",
      "Tighten the temporal spacing between dialogue clips to assemble a fast-paced, high-retention rough cut sequence.",
    ],
  },
  {
    id: 89,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Computational Audio Enhancement & Export",
    chapter: "Phase 3 | Chapter 5",
    chapterTitle: "Non-Linear Editing System Workspace",
    week: 14,
    chapterColor: "#9A3324",
    bullets: [
      "Deploy the Essential Sound panel's Enhanced Speech algorithms to remove room echo and background hum instantly.",
      "Balance baseline audio frequencies to ensure your vocal track remains punchy, clear, and perfectly centered.",
      "Export a clean, high-bitrate master edit file explicitly configured to be port-ready for motion design staging in After Effects.",
    ],
  },
  // ─── Phase 3 | Chapter 6 : Motion Design in After Effects (Week 15) ───
  {
    id: 90,
    icon: PATH_ICON90,
    modelIcon: MODEL_ICON90,
    title: "After Effects Workspace & AEUX Porting",
    chapter: "Phase 3 | Chapter 6",
    chapterTitle: "Keyframes & Vector Asset Porting",
    week: 15,
    chapterColor: "#1A6B5A",
    bullets: [
      "Onboard into the After Effects workspace layout, mapping composition panels, multi-layered timelines, and effects controls.",
      "Deploy the AEUX plugin framework to instantly transfer raw vector UI components and layout paths directly out of Figma.",
      "Convert imported layers cleanly into native, editable After Effects shape groups to protect vector scalability.",
    ],
     hintText: "After Effects",
    hintOffsetX: 30,  
    hintOffsetY: 50,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 91,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Spatial Mechanics & The Graph Editor",
    chapter: "Phase 3 | Chapter 6",
    chapterTitle: "Keyframes & Vector Asset Porting",
    week: 15,
    chapterColor: "#1A6B5A",
    bullets: [
      "Master spatial properties, interpolations, and basic transform properties to anchor your baseline animation tracks.",
      "Open the native Graph Editor console to manipulate value curves and speed charts manually.",
      "Apply custom interpolation handles to generate highly professional, organic asset easing states.",
    ],
  },
  {
    id: 92,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Production Plugin Integration",
    chapter: "Phase 3 | Chapter 6",
    chapterTitle: "Keyframes & Vector Asset Porting",
    week: 15,
    chapterColor: "#1A6B5A",
    bullets: [
      "Integrate industry-standard motion graphics utilities, including Animation Composer, Boombox, and Motion 4.",
      "Use automated transformation rigs and shortcut tool palettes to eliminate repetitive keyframing operations.",
      "Synchronize production sound asset libraries directly to visual markers to maximize layout impacts.",
    ],
  },
  // ─── Phase 3 | Chapter 7 : Brand Asset Animation (Week 15) ───
  {
    id: 93,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Logo Rigs & Pinterest Moodboarding",
    chapter: "Phase 3 | Chapter 7",
    chapterTitle: "Kinetic Brand Packaging",
    week: 15,
    chapterColor: "#784212",
    bullets: [
      "Collect a curated motion design moodboard from Pinterest to map dynamic layout paths and visual trends.",
      "Animate your company logo or personal brand asset using layered reveal tracks, mask configurations, and trim paths.",
      "Package your animated logo into a reusable, transparent lower-third render block to use across future projects.",
    ],
  },
  {
    id: 94,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Reel Template Design & Layout Arrays",
    chapter: "Phase 3 | Chapter 7",
    chapterTitle: "Kinetic Brand Packaging",
    week: 15,
    chapterColor: "#784212",
    bullets: [
      "Build high-conversion, responsive motion graphic templates tailored for 9:16 Instagram Reels and YouTube Shorts.",
      "Coordinate layered typography sweeps, shape banners, and image containers to showcase your startup's products.",
      "Apply custom color variables and expressions to change template parameters instantly across multiple frames.",
    ],
  },
  {
    id: 95,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Veed.io Captions & Cinematic Impact",
    chapter: "Phase 3 | Chapter 7",
    chapterTitle: "Kinetic Brand Packaging",
    week: 15,
    chapterColor: "#784212",
    bullets: [
      "Export your primary video cut to Veed.io to instantly generate frame-accurate, hardcoded subtitle tracks.",
      "Apply stylized, high-contrast kinetic caption layouts to protect mobile accessibility and maximize content retention loops.",
      "Inject dynamic transitions and atmospheric background sound elements to make your final video timeline pop.",
    ],
  },
  // ─── Phase 3 | Chapter 8 : Multi-Platform Export & Publishing (Week 15) ───
  {
    id: 96,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Render Settings & Archive Templates",
    chapter: "Phase 3 | Chapter 8",
    chapterTitle: "Distribution Mastering & Pipeline Launch",
    week: 15,
    chapterColor: "#4A235A",
    bullets: [
      "Set up the After Effects Render Queue and Adobe Media Encoder paths to output high-bitrate, web-optimized MP4 files.",
      "Export dedicated, clean Master File archives alongside modular template layers for fast iteration loops later.",
      "Configure compression balances to guarantee rich color values and sharp text lines across all social screens.",
    ],
  },
  {
    id: 97,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "High-Click Cover & Thumbnail Fabrication",
    chapter: "Phase 3 | Chapter 8",
    chapterTitle: "Distribution Mastering & Pipeline Launch",
    week: 15,
    chapterColor: "#4A235A",
    bullets: [
      "Freeze and extract high-impact canvas frames out of your finished video sequence to use as baseline covers.",
      "Compose high-contrast typography stamps and crisp asset outlines inside Figma to optimize your click-through rates.",
      "Balance thumbnail aspect limits to ensure complete readability across both grid feeds and discovery streams.",
    ],
  },
  {
    id: 98,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Production Publishing Sequence",
    chapter: "Phase 3 | Chapter 8",
    chapterTitle: "Distribution Mastering & Pipeline Launch",
    week: 15,
    chapterColor: "#4A235A",
    bullets: [
      "Execute your first official asset release loop by uploading your completed 9:16 vertical Reel to live media channels.",
      "Author engagement-optimized copywriting titles, keyword tags, and strategic platform links to route incoming traffic.",
      "Audit early distribution metrics to analyze audience retention spikes and prepare code-free media adjustments.",
    ],
  },
  {
    id: 99,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Multimodality Spatial Composite",
    chapter: "Phase 3 | Chapter 8",
    chapterTitle: "Distribution Mastering & Pipeline Launch",
    week: 15,
    chapterColor: "#4A235A",
    bullets: [
      "Inject your generative AI video assets and cinematic clips smoothly into physical environment layers while maintaining perfect perspective locks.",
      "Utilize advanced Rotobrush algorithms and multi-layered bezier masking tracks to isolate foreground elements and cleanly wrap AI graphics behind real-world subjects.",
      "Architect complex typography animation arrays featuring expressions, kinetic tracking maps, and per-character lighting interactions to achieve a high-end look.",
    ],
  },
  // ─── Phase 3 | Chapter 10 : Creator Economy (Week 17) ───
  {
    id: 100,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Quantity Game & Platform Algorithms",
    chapter: "Phase 3 | Chapter 10",
    chapterTitle: "Platform Algorithms & Case Studies",
    week: 17,
    chapterColor: "#2D1B69",
    bullets: [
      "Study the underlying mechanics of the creator economy across Instagram Reels and YouTube Shorts.",
      "Deconstruct short-form content distribution rules to exploit search algorithms and audience distribution waves.",
      "Build a high-volume output engine to optimize early audience retention tests across networks.",
    ],
  },
  {
    id: 101,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Product Growth Architecture",
    chapter: "Phase 3 | Chapter 10",
    chapterTitle: "Platform Algorithms & Case Studies",
    week: 17,
    chapterColor: "#2D1B69",
    bullets: [
      "Break down the exact real-world content growth strategies deployed to scale Iconscout and Cashfree systems.",
      "Map custom growth flywheels to systematically tie video views to direct landing page checkouts.",
      "Build an action matrix to customize these corporate tech strategies for your own project launch.",
    ],
  },
  {
    id: 102,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Creator Moodboard Strategy",
    chapter: "Phase 3 | Chapter 10",
    chapterTitle: "Platform Algorithms & Case Studies",
    week: 17,
    chapterColor: "#2D1B69",
    bullets: [
      "Build an algorithmic competitor board by analyzing 5 elite creators posting regularly in your direct market.",
      "Isolate their layout formats, editing structures, pacing frameworks, and sound design layers to build a design moodboard.",
      "Leverage premium profile options to unlock deep metrics and reverse-engineer successful viral styles.",
    ],
  },
  // ─── Phase 3 | Chapter 11 : Sketch Writing & Publishing (Week 17) ───
  {
    id: 103,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Deep Thaker Sketch Systems & 5-Word Hooks",
    chapter: "Phase 3 | Chapter 11",
    chapterTitle: "30-Second Content Architecture",
    week: 17,
    chapterColor: "#0F3460",
    bullets: [
      "Study the Deep Thaker playbook for crafting highly engaging 30-second comedic or informative sketches.",
      "Hardcode hyper-impactful 5-word hooks designed to capture viewers instantly within the critical first seconds.",
      "Map out a production schedule to write, refine, and plan 10 modular short-form videos completely on paper from home.",
    ],
  },
  {
    id: 104,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Fast-Track Post-Production Flow",
    chapter: "Phase 3 | Chapter 11",
    chapterTitle: "30-Second Content Architecture",
    week: 17,
    chapterColor: "#0F3460",
    bullets: [
      "Record your scripted sketch takes and execute high-speed dialogue cutting loops inside Premiere Pro.",
      "Move your layout to After Effects to overlay custom-animated motion graphics and brand assets seamlessly.",
      "Synchronize dynamic typography setups and audio hits to maximize video engagement retention.",
    ],
  },
  {
    id: 105,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Visual Identity Publishing Loops",
    chapter: "Phase 3 | Chapter 11",
    chapterTitle: "30-Second Content Architecture",
    week: 17,
    chapterColor: "#0F3460",
    bullets: [
      "Fabricate high-contrast video cover assets in Figma to maintain a cohesive, professional profile identity.",
      "Run a seed release sequence by publishing your short across close channels and masterminds to capture early feedback.",
      "Use initial tracking data to refine visual messaging choices before launching paid media budgets.",
    ],
  },
  // ─── Phase 3 | Chapter 12 : Paid Acquisition & Meta Ads (Week 17) ───
  {
    id: 106,
    icon: PATH_ICON106,
    modelIcon: MODEL_ICON106,
    title: "Meta Ads Campaign Infrastructure",
    chapter: "Phase 3 | Chapter 12",
    chapterTitle: "Algorithmic Campaign Operations",
    week: 17,
    chapterColor: "#1B4332",
    bullets: [
      "Set up your Meta Business Manager suite, pixel tracking tags, and standard tracking configurations.",
      "Structure optimization funnels designed to push high-converting vertical video creatives to target buyers.",
      "Balance ad spends across diverse testing hooks to lower your customer acquisition costs.",
    ],
     hintText: "Meta Ads ✨",
    hintOffsetX: 30,  
    hintOffsetY: 50,
    arrowRotate: '80deg', 
    arrowTop: -20,       
    arrowLeft: -15,
  },
  {
    id: 107,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Meta Ads MCP Server Connection",
    chapter: "Phase 3 | Chapter 12",
    chapterTitle: "Algorithmic Campaign Operations",
    week: 17,
    chapterColor: "#1B4332",
    bullets: [
      "Install and configure a Model Context Protocol (MCP) server to connect Meta Ads APIs straight to your AI workspace.",
      "Allow terminal-driven engineering agents to monitor ad spends, pull analytics, and check performance matrices.",
      "Run terminal-driven diagnosis checks to solve protocol connection errors and manage data tunnels securely.",
    ],
  },
  {
    id: 108,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Autonomous Content Distribution & Scheduling",
    chapter: "Phase 3 | Chapter 12",
    chapterTitle: "Algorithmic Campaign Operations",
    week: 17,
    chapterColor: "#1B4332",
    bullets: [
      "Use plain English terminal instructions to build, review, and schedule mass marketing content campaigns.",
      "Program AI agents to evaluate ad metrics in real-time, instantly adjusting bids or swapping slow assets.",
      "Link your scheduling calendar arrays directly to automated distribution engines for continuous web visibility.",
    ],
  },
  // ─── Final Phase | Chapter 1 : Real-World Networking (Week 18) ───
  {
    id: 109,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Real-World Event Presence",
    chapter: "Final Phase | Chapter 1",
    chapterTitle: "Live Event Integration & Public Performance",
    week: 18,
    chapterColor: "#9A3324",
    bullets: [
      "Learn how to confidently introduce yourself, network fluidly, and share active Academy projects during live local tech conferences.",
      "Master body language, crisp voice modulation, and elevator pitch dynamics to seamlessly explain your design engineering builds.",
      "Establish key industry connections to build an early feedback loop for your startup before concluding the curriculum.",
    ],
  },
  {
    id: 110,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Stage Comfort & Rejection Mechanics",
    chapter: "Final Phase | Chapter 1",
    chapterTitle: "Live Event Integration & Public Performance",
    week: 18,
    chapterColor: "#9A3324",
    bullets: [
      "Build bulletproof psychological comfort on stage by practicing physical breathing anchors, eye contact zones, and posture stability.",
      "Master how to handle live rejection, unexpected technical errors, and critical audience pushback during an open mic presentation gracefully.",
      "Learn to pivot unexpected stage friction into high-value engagement opportunities without breaking your presentation flow.",
    ],
  },
  {
    id: 111,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Humor & Joke Delivery Engineering",
    chapter: "Final Phase | Chapter 1",
    chapterTitle: "Live Event Integration & Public Performance",
    week: 18,
    chapterColor: "#9A3324",
    bullets: [
      "Learn the foundational rules of narrative comedy, timing beats, and writing relatable jokes customized for high-stress business crowds.",
      "Master how to deliver targeted jokes naturally to instantly break tension and command full room attention.",
      "Practice a structured framework to write, edit, and perform your own original presentation jokes live on stage during mock demo days.",
    ],
  },
  // ─── Final Phase | Chapter 2 : Investor Pitch Decks (Week 18) ───
  {
    id: 112,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Pitch Deck Foundations & Strategic Anatomy",
    chapter: "Final Phase | Chapter 2",
    chapterTitle: "High-Conversion Capital Raising",
    week: 18,
    chapterColor: "#1A6B5A",
    bullets: [
      "Deconstruct the exact financial and narrative definition of a pitch deck to understand exactly why founders use them to raise capital.",
      "Map out a visually stunning, minimalist layout strategy that favors crisp typographic hierarchies over heavy, cluttered imagery.",
      "Study how to communicate massive product engineering visions into simple, high-impact value propositions.",
    ],
  },
  {
    id: 113,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Corporate Teardowns & 7-Slide Blueprints",
    chapter: "Final Phase | Chapter 2",
    chapterTitle: "High-Conversion Capital Raising",
    week: 18,
    chapterColor: "#1A6B5A",
    bullets: [
      "Collect and meticulously study 5 legendary pitch deck examples from massive global companies to reverse-engineer their success.",
      "Construct a lean, hyper-optimized presentation deck featuring a minimum of 7 core slides covering Problem, Solution, Traction, and Market.",
      "Enforce strict minimal design principles across your layouts inside Figma to protect brand authority.",
    ],
  },
  {
    id: 114,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Pitchdeck.pdf Export & Investor Launch",
    chapter: "Final Phase | Chapter 2",
    chapterTitle: "High-Conversion Capital Raising",
    week: 18,
    chapterColor: "#1A6B5A",
    bullets: [
      "Package your finished presentation boards and export a pristine, web-optimized Pitchdeck.pdf file ready for distribution.",
      "Learn how to strategically target, cold-pitch, and safely email your PDF file straight to active angel investors and venture networks.",
      "Combine your built social media brand footprint with your pitch document to maximize investor confidence and close funding rounds.",
    ],
  },
  // ─── Final Phase | Mindset : Vipasna & Graduation (Week 19) ───
  {
    id: 115,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The 10-Day Mindset Isolation Track",
    chapter: "Final Phase | Mindset",
    chapterTitle: "Deep Psychological Processing & Calibrations",
    week: 19,
    chapterColor: "#784212",
    bullets: [
      "Disconnect completely from tech infrastructure to undergo a deep, 10-day intensive Vipasna meditation retreat framework.",
      "Use this isolated, peaceful time to deeply reflect on the systems you have built and plan how to scale them to the next level.",
      "Calibrate your inner psychology to unlock a grounded, hyper-focused state of execution.",
    ],
  },
  {
    id: 116,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Core Pillars of the Human Element",
    chapter: "Final Phase | Mindset",
    chapterTitle: "Deep Psychological Processing & Calibrations",
    week: 19,
    chapterColor: "#784212",
    bullets: [
      "Study the core visual nodes of inner engineering: Self-Awareness, Living in the Moment, and true Peace.",
      "Cultivate an unshakeable Stoic mindset to easily process market volatility, product friction, and everyday business stress.",
      "Align your work goals with genuine personal Happiness to protect your mental health across your career.",
    ],
  },
  {
    id: 117,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Superhuman Product Realignment",
    chapter: "Final Phase | Mindset",
    chapterTitle: "Deep Psychological Processing & Calibrations",
    week: 19,
    chapterColor: "#784212",
    bullets: [
      "Return from mental isolation with total clarity, shedding coding anxieties and design blockades completely.",
      "Merge your sharpened cognitive stamina with your technical engineering tools to operate like a true Superhuman.",
      "Lock down your absolute final product alterations ahead of the live investor presentation.",
    ],
  },
  // ─── Final Phase | Graduation (Week 19) ───
  {
    id: 118,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Live Investor Demo Day Pitch",
    chapter: "Final Phase | Graduation",
    chapterTitle: "Live Fundraising Capital & Beyond",
    week: 19,
    chapterColor: "#4A235A",
    bullets: [
      "Step onto the final stage to deliver your polished startup presentation deck directly in front of active venture investors.",
      "Defend your technical architecture, design assets, and marketing pipeline choices dynamically under live evaluation.",
      "Position your product clearly to secure early fundraising rounds valued from ₹50K up to ₹2.5 Lakh.",
    ],
  },
  {
    id: 119,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "Graduation Ceremonies & Network Locking",
    chapter: "Final Phase | Graduation",
    chapterTitle: "Live Fundraising Capital & Beyond",
    week: 19,
    chapterColor: "#4A235A",
    bullets: [
      "Celebrate the successful completion of the intensive Academy curriculum with your peers and engineering mentors.",
      "Formally lock down your active alumni portal credentials to access lifelong masterminds and collaborative talent pools.",
      "Secure signed validation certificates confirming your mastery over advanced design engineering systems.",
    ],
  },
  {
    id: 120,
    icon: PATH_ICON,
    modelIcon: MODEL_ICON,
    title: "The Infinite Journey: Initializing Life 2.0",
    chapter: "Final Phase | Graduation",
    chapterTitle: "Live Fundraising Capital & Beyond",
    week: 19,
    chapterColor: "#4A235A",
    bullets: [
      "Conclude your structured academic path and officially mark the grand boundary line of your new life.",
      "Deploy your fully funded, self-contained interactive web platforms and automated marketing systems into the real world.",
      "Take command of the marketplace as an elite creative entrepreneur, scaling your business indefinitely.",
    ],
  },
];
